[project]
name = "secure-agents-for-smart-city"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.111.0",
    "langchain==1.2.0",
    "langchain-openai==1.1.6",
    "pandas>=3.0.0",
    "prometheus-client>=0.20.0",
    "pydantic>=2.7.3",
    "python-dotenv>=1.0.1",
    "requests==2.32.3",
    "streamlit>=1.50.0",
    "uvicorn>=0.30.1",
    "fastmcp>=0.3.0",
]

[project.scripts]
fiware-mcp-server = "smartcity.infra.fiware_mcp.server:main"
pump-mcp-server = "smartcity.infra.pump_mcp.server:main"
weather-mcp-server = "smartcity.infra.weather_mcp.server:main"
