"""Prometheus metrics for the MAPE-K loop.

Counters and histograms cover the per-stage and per-component instrumentation
required for the latency-impact and guardrail-effectiveness experiments
documented in the README.
"""

from __future__ import annotations

import time
from contextlib import contextmanager
from typing import Iterator, Optional

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    CollectorRegistry,
    Counter,
    Histogram,
    generate_latest,
)

REGISTRY = CollectorRegistry(auto_describe=True)

LATENCY_BUCKETS = (
    0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0,
)

PLANS_TOTAL = Counter(
    "smartcity_plans_total",
    "Candidate plans generated by the planner.",
    ("scenario", "risk_level", "source"),
    registry=REGISTRY,
)

POLICY_DECISIONS_TOTAL = Counter(
    "smartcity_policy_decisions_total",
    "Policy decisions issued by the policy engine.",
    ("approval_mode", "risk_level", "allowed", "source"),
    registry=REGISTRY,
)

EXECUTIONS_TOTAL = Counter(
    "smartcity_executions_total",
    "Plan executions attempted by the executor, grouped by outcome.",
    ("status",),
    registry=REGISTRY,
)

MCP_CALLS_TOTAL = Counter(
    "smartcity_mcp_calls_total",
    "MCP tool invocations.",
    ("method", "status"),
    registry=REGISTRY,
)

ERRORS_TOTAL = Counter(
    "smartcity_errors_total",
    "Errors raised inside the MAPE-K loop, grouped by component.",
    ("component", "kind"),
    registry=REGISTRY,
)

STAGE_DURATION_SECONDS = Histogram(
    "smartcity_stage_duration_seconds",
    "Wall-clock duration of MAPE-K stages.",
    ("stage", "component"),
    buckets=LATENCY_BUCKETS,
    registry=REGISTRY,
)


@contextmanager
def stage_timer(
    stage: str, component: str, on_finish: Optional[callable] = None
) -> Iterator[dict]:
    """Time a block of work and emit it as a stage_duration_seconds sample.

    The yielded dict can be mutated by the caller; the final ``duration_ms``
    is filled in on exit and is convenient to push into structured logs and
    audit entries alongside the metric.
    """
    started = time.perf_counter()
    sample: dict = {"stage": stage, "component": component}
    try:
        yield sample
    finally:
        duration = time.perf_counter() - started
        STAGE_DURATION_SECONDS.labels(stage=stage, component=component).observe(
            duration
        )
        sample["duration_ms"] = round(duration * 1000.0, 3)
        if on_finish is not None:
            on_finish(sample)


def render_latest() -> tuple[bytes, str]:
    """Render the registry in the Prometheus text exposition format."""
    return generate_latest(REGISTRY), CONTENT_TYPE_LATEST
